spring:
  datasource:
    username: kurt
    url: jdbc:postgresql://177.74.2.105:5432/comercial_desenv
    password: cosanpa123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}
server:
  error:
    include-stacktrace: never
