package br.gov.pa.cosanpa.api.dto.faturamento

import java.math.BigDecimal

data class QualidadeAguaDTO(
    val id: Int? = null,
    val anoMesReferencia: Int? = null,
    val numeroIndiceTurbidez: BigDecimal? = null,
    val numeroCloroResidual: BigDecimal? = null,
    val numeroIndicePh: BigDecimal? = null,
    val numeroIndiceCor: BigDecimal? = null,
    val numeroIndiceFluor: BigDecimal? = null,
    val numeroIndiceFerro: BigDecimal? = null,
    val numeroIndiceColiformesTotais: BigDecimal? = null,
    val numeroIndiceColiformesFecais: BigDecimal? = null,
    val numeroNitrato: BigDecimal? = null,
    val numeroIndiceAlcalinidade: BigDecimal? = null,
    val quantidadeTurbidezExigidas: Int? = null,
    val quantidadeTurbidezAnalisadas: Int? = null,
    val quantidadeTurbidezConforme: Int? = null,
    val quantidadeCorExigidas: Int? = null,
    val quantidadeCorAnalisadas: Int? = null,
    val quantidadeCorConforme: Int? = null,
    val quantidadeCloroExigidas: Int? = null,
    val quantidadeCloroAnalisadas: Int? = null,
    val quantidadeCloroConforme: Int? = null,
    val quantidadeFluorExigidas: Int? = null,
    val quantidadeFluorAnalisadas: Int? = null,
    val quantidadeFluorConforme: Int? = null,
    val quantidadeColiformesTotaisExigidas: Int? = null,
    val quantidadeColiformesTotaisAnalisadas: Int? = null,
    val quantidadeColiformesTotaisConforme: Int? = null,
    val quantidadeColiformesFecaisExigidas: Int? = null,
    val quantidadeColiformesFecaisAnalisadas: Int? = null,
    val quantidadeColiformesFecaisConforme: Int? = null,
    val quantidadeColiformesTermotolerantesExigidas: Int? = null,
    val numeroIndiceColiformesTermotolerantes: Int? = null,
    val quantidadeColiformesTermotolerantesAnalisadas: Int? = null,
    val quantidadeColiformesTermotolerantesConforme: Int? = null,
    val quantidadeAlcalinidadeExigidas: Int? = null,
    val quantidadeAlcalinidadeAnalisadas: Int? = null,
    val quantidadeAlcalinidadeConforme: Int? = null,
    val descricaoFonteCaptacao: String? = ""
)
