package br.gov.pa.cosanpa.api.view.endereco

data class DadosEndereco(
    val logradouroNome: String?,
    val logradouroTipoDescricao: String?,
    val logradouroTituloDescricao: String?,
    val bairroId: Int?,
    val bairroNome: String?,
    val municipioId: Int?,
    val municipioNome: String?,
    val unidadeFederacaoId: Int?,
    val unidadeFederacaoSigla: String?,
    val enderecoReferenciaDescricao: String?,
    val cepId: Int?,
    val cepLogradouro: String?,
    val cepDescricaoTipoLogradouro: String?,
    val cepBairro: String?,
    val cepMunicipio: String?,
    val cepSigla: String?,
    val cepCodigo: Int?,
    val imovelNumero: String?,
    val imovelComplementoEndereco:  String?,
    val logradouroId: Int?,
    val logradouroCepId: Int?,
    val logradouroBairroId: Int?,
    val logradouroTipoDescricaoAbreviada: String?,
    val logradouroTituloDescricaoAbreviada: String?,
    val enderecoReferenciaDescricaoAbreviada: String?,
    val enderecoReferenciaId: Int?,
    val perimetroInicialId: Int?,
    val perimetroInicialNome: String,
    val logradouroTipoPerimetroInicialDescricaoAbreviada: String,
    val logradouroTituloPerimetroInicialDescricaoAbreviada: String,
    val perimetroFinalId: Int?,
    val perimetroFinalNome: String?,
    val logradouroTipoPerimetroFinalDescricaoAbreviada: String?,
    val logradouroTituloPerimetroFinalDescricaoAbreviada: String?,
)
